(DATA  a)
(DATA  b)
(DATA  c)
(FUNCTION  main  [(int argc)]
  (BB 2
    (OPER 3 Func_Entry []  [])
  )
  (BB 3
    (OPER 4 Mov [(r 5)]  [(i 2)])
    (OPER 5 Mov [(r 2)]  [(r 5)])
    (OPER 6 Mov [(r 6)]  [(i 2)])
    (OPER 7 Mov [(r 3)]  [(r 6)])
    (OPER 8 Add_I [(r 7)]  [(r 2)(r 3)])
    (OPER 9 Mov [(r 4)]  [(r 7)])
    (OPER 10 Mov [(m RetReg)]  [(r 4)])
    (OPER 11 Jmp []  [(bb 1)])
  )
  (BB 4
    (OPER 12 Mov [(r 8)]  [(i 3)])
    (OPER 13 Mov [(r 4)]  [(r 8)])
    (OPER 14 Mov [(r 9)]  [(i 1)])
    (OPER 15 Pass []  [(r 9)])
    (OPER 16 Mov [(r 10)]  [(i 2)])
    (OPER 17 Pass []  [(r 10)])
    (OPER 18 Mov [(r 11)]  [(i 3)])
    (OPER 19 Pass []  [(r 11)])
    (OPER 20 JSR []  [(s x)] [(size 3)])
  )
  (BB 5
  )
  (BB 1
    (OPER 1 Func_Exit []  [])
    (OPER 2 Return []  [(m RetReg)])
  )
)
